application: trim-mariner-422
version: 1
runtime: go
api_version: go1

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*\.(xml|css|txt))
  secure: always

- url: /admin/.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always
